name: Test

on:
  workflow_dispatch:
  pull_request_target:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2

      - name: Run tests
        run: go test -fuzz Fuzz -fuzztime 10s
